### ISSUE TITLE
Issues with the MS_changeNames() function

### ISSUE THREAD

**Issue by dBenedek** [AndreaRMICL/MetaboSignal#1]
Hello,

For most of the genes, the `MS_changeNames()` function works correctly.
Example:

```r

> MS_changeNames("126374", "hsa")
[1] "WTIP"
```

However, for some genes, it only works, if I provide the gene ID as `hsa:XYZ`.
Example:

```r
> MS_changeNames("11283", "hsa")
[1] "11283"
Warning message:
Unable to map 1 of 1 requested IDs. 

> MS_changeNames("hsa:11283", "hsa")
[1] "CYP4F8"

> MS_changeNames("102724594", "hsa")
[1] "102724594"
Warning message:
Unable to map 1 of 1 requested IDs. 

> MS_changeNames("hsa:102724594", "hsa")
[1] "U2AF1L5"
```

I guess this could be easily adjusted in the code.

Best,
Benedek

**Comment by AndreaRMICL** [comment]
Hi!

Thank you very much for your comment. 

The reason why this happens is because when you use `hsa:11283` it tries to map the gene symbol using the KEGG API. However, when you query the ENTREZID directly it uses the `mapIds()` function from `AnnotationDbi` so it's expected that the results could be different in some cases. I encourage you to use the KEGG ID option in the first place (e.g. `hsa:11283`)and if it that returns NA you can further try to map it just querying the ENTREZID (e.g. `11283`)

Hope it helps!

Andrea

**Comment by dBenedek** [comment]
Hello,

Thank you for the quick reply!
Another minor comment: some genes do not have gene symbols ([example](http://rest.kegg.jp/get/hsa:107987478)) so in these cases retrieving gene symbols is also not possible, not surprisingly.

Best,
Benedek

**Comment by AndreaRMICL** [comment]
Thank you! I think there is not much that can be done in those cases :(
