### ISSUE TITLE
Having problem when using MS_keggNetwork

### ISSUE THREAD

**Issue by Yun1229** [AndreaRMICL/MetaboSignal#3]
Hello,

I am encountering an error while using the MS_keggNetwork function to build a metabolic pathway network for Pseudomonas aeruginosa. 
The code I used:

> ` MS_keggNetwork(signaling_paths = signaling_paths,metabo_paths = metabo_paths, expand_genes = T)`

Then I got a message stating that 

> Some path IDs were not used: pae00190,pae01100

The output network table is correct for the other pathways though. 
However, I also need the network to include the pathway pae00190 and pae01100.
  
Could you please provide any guidance on how to solve this problem?
Are there any additional troubleshooting steps that I can take to resolve this issue?
Thank you for your help.

**Comment by AndreaRMICL** [comment]
Hi Yun!

So the reason why this happens is because: `pae00190` doesn't really have edges (https://www.genome.jp/dbget-bin/www_bget?pae00190) and `pae01100` is the general metabolic map (which has issues with directionality, so it's better to derive it from all other paths)

Hope it makes sense

Best

Andrea

**Comment by Yun1229** [comment]
Ok I see!
Thank you so much :)
